apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1 # Allow 1 pod to be unavailable during update
      maxSurge: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: vivekpeerbits/react-app
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  type: NodePort # <-- Changed from ClusterIP to NodePort
  selector:
    app: react-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080 # <-- You can choose a custom port between 30000–32767
