name: Build and Push Docker Image

# Triggers the workflow on push or pull request to the main branch
on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository.
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build the Docker image..
    - name: Build and tag Docker image
      run: |
        docker build . -t ${{ secrets.DOCKER_USERNAME }}/react-app:latest

    # Push the Docker image to Docker Hub
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/react-app:latest

    # Decode SSH key
    - name: Decode SSH key
      run: |
        echo "${{ secrets.EC2_SSH_KEY_B64 }}" | base64 -d > key.pem
        chmod 600 key.pem

    # Deploy to EC2
    - name: SSH and deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker pull ${{ secrets.DOCKER_USERNAME }}/react-app:latest
          docker stop react-app || true && docker rm react-app || true
          docker run -d --name react-app -p 80:80 ${{ secrets.DOCKER_USERNAME }}/react-app:latest
        EOF
